### ISSUE TITLE
Add Orchard Collaboration modules

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#13]
Its repo is here: [https://github.com/siyamandayubi/Orchardcollaboration](https://github.com/siyamandayubi/Orchardcollaborationt). The problem with it is that it contains multiple modules, which are can be properly used with Orchard 1.10: because with Orchard 1.10 special module folders can be given, thus we don't need to do anything with the cloned repo, and we can use it from where it is.

An important detail that there is a setup module in which this recipe will perform the whole configuration:
[https://orchardcollaboration.codeplex.com/SourceControl/latest#src/Orchard.Web/Modules/Orchard.CRM.ProjectSetup/Recipes/orchardcollaboration.recipe.xml](https://orchardcollaboration.codeplex.com/SourceControl/latest#src/Orchard.Web/Modules/Orchard.CRM.ProjectSetup/Recipes/orchardcollaboration.recipe.xml). This is a setup recipe, so we need to decide if we want it to show it to the users or not. This also enabling the Bootstrap theme (which is the PJS.Bootstrap and already available for the tenants).

**Comment by Piedone** [comment]
We won't work on extending the O1 DotNest sites like this anymore.
