### ISSUE TITLE
Media Theme deployment should be able to handle themes from Gallery

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#14]
I.e. it shouldn't handle just zips, where the Theme.txt can only be one folder deep, but we add support especially for the Gallery (where is a zip with .nupgk file extension, and also the theme is in a certain folder inside the package).

Problem is that inside the Gallery themes there are cshtml templates, which aren't usable on DotNest.

**Comment by Piedone** [comment]
We can't do this without cshtml support, which we won't have.
