### ISSUE TITLE
Simpler and stronger integration of Google Analytics

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#16]
In a new module it should be allowed for the user to wire Google Analytics to his site even simpler than with the Simple Analytics module. E.g. there has be a textbox, to where one can copy the Analytics script, from which we parsing out the ID and we always use the freshest recommended script (without having the user to migrate).

Also we could create widgets for the dashboard (See: [https://orchard.codeplex.com/workitem/18227](https://orchard.codeplex.com/workitem/18227)), which are showing embedded the most important metrics from Google Analytics (See: [https://developers.google.com/analytics/devguides/reporting/embed/v1/](https://developers.google.com/analytics/devguides/reporting/embed/v1/)).

**Comment by Piedone** [comment]
We won't work on extending the O1 DotNest sites like this anymore. This is part of OC though.
