### ISSUE TITLE
Blog walkthrough recipe (NEST-347)

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#17]
Making a recipe, that guides through how to create and configure a blog, with the help of a JS walkthrough. E.g. how to create taxonomy menu (managing menus, widgets), how to use analytics, setting a theme, media library usage, and setting up other useful modules.

1. Along the lines of TryOrchard? Same liquid solution or something else maybe?
2. Shall we add any other content besides the ones in the default recipe?
3. At the end of the walkthrough delete the content items and overrides which are used by the walkthrough.

There could be other similar thematic walkthroughs, too. If someone uses DotNest as a platform, they can get this walkthrough, whereby they could save on any further training.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-347)

**Comment by Piedone** [comment]
This will be covered by https://github.com/Lombiq/DotNest-Support/issues/15.
