### ISSUE TITLE
Countdown bar at the top of the TryOrchard demo sites instead of homepage countdown widget (NEST-345)

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#20]
On the [TryOrchard](http://tryorchard.net/) demo sites we should replace the countdown widget with a countdown bar at the top as an overlay, so that is always visible (on admin, too). It can be closed.

This will be interesting again with the Orchard Core successor of TryOrchard.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-345)

**Comment by Piedone** [comment]
We'll have something else for Orchard Core, so this won't be interesting.
