### ISSUE TITLE
Add Shaun's client-side goodies

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#22]
- [http://gallery.orchardproject.net/List/Modules/Orchard.Module.BigFont.TheThemeMachineDesigner](http://gallery.orchardproject.net/List/Modules/Orchard.Module.BigFont.TheThemeMachineDesigner) (interesting to play with as a beginner developer)
- [http://gallery.orchardproject.net/List/Themes/Orchard.Theme.Bootstrap_3_1_1_SimpleBlog](http://gallery.orchardproject.net/List/Themes/Orchard.Theme.Bootstrap_3_1_1_SimpleBlog)
- http://gallery.orchardproject.net/List/Modules/Orchard.Module.BigFont.Bootstrap.Components[http://gallery.orchardproject.net/List/Modules/Orchard.Module.BigFont.Bootstrap.Components](url)

Source: [https://github.com/bigfont/orchard-cms-modules-and-themes/tree/master/src/Orchard.Web/Themes](https://github.com/bigfont/orchard-cms-modules-and-themes/tree/master/src/Orchard.Web/Themes)

**Comment by Piedone** [comment]
We won't work on extending the O1 DotNest sites like this anymore.
