### ISSUE TITLE
Payment method CRUD operations (NEST-350)

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#3]
I.e. to be able to edit/delete the existing payment method (billing address and card details), add new ones, and select the default.

## Tasks

- Modify the payment method.

    - If the user wants to change the card number or the CVV (or the expiration date, if we mask it, too), then the user should re-enter it again. If the user isn’t editing this kind of data, we should leave them unchanged. (With credit card e.g. a valid use-case is when editing only the CVV and the expiration date: expired cards can be replaced in a way by the bank that they only change the expiration date and the CVV, but they leave the card number and the name the same.)
    -  On DotNest it’s a required use-case that the user should be able to change the subscribed site’s payment method on the given custom domain usage in a way, that the end of the existing subscription is extended with the new end of subscription. Implement the necessary changes on DotNest.Frontend, too. (Of course, if a payment method is used on multiple sites, then the edit of the payment method will change the others too seemingly, thus they’re the same.) A general and DotNest-related feature is that I be able to list and edit all my payment methods from a link, not just when I’m going to pay.

- The possibility to delete the whole payment method.
- The possibility to set the default payment (requires some digging in the Braintree spec about this).
- The possibility of adding a new payment method on a separate page (it could be in the create transaction/subscription page, this is independent).
- Independent customer editor interface (basically it’s the same as the create transaction/subscription page, but when you save only the customer data should be updated).

[Jira issue](https://lombiq.atlassian.net/browse/NEST-350)

**Comment by Piedone** [comment]
We'll use Orchard Core Commerce in the future instead.
