### ISSUE TITLE
Where is module gallery

### ISSUE THREAD

**Issue by lbcsy** [Lombiq/DotNest-Support#35]
Hi,
I could not find module gallery in my Orchard CMS, is it not supported in this hosting?

Regards,
Bo

**Comment by Piedone** [comment]
It's indeed not supported. Due to the multi tenant nature of DotNest you can't install modules or themes the usual way, but you can still write a bit different themes for your sites. See: https://dotnest.com/knowledge-base/topics/limitations

**Comment by Piedone** [comment]
Please reopen if you have further questions.
