### ISSUE TITLE
 CORS policy: No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by oldbrazil** [Lombiq/DotNest-Support#38]
Hi folks, 
I have several blogs on dotnest (great!)
But when monitoring the page load with Chrome Dev Tools, I see that some files cannot be served. I get the exception : 

`Access to font at 'https://dotneststatic.com/Themes/PJS.Bootstrap/Styles/font-awesome-4.3.0/fonts/fontawesome-webfont.woff2?v=4.3.0' from origin 'https://codeflow.dotnest.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

How can I serve files (custom scripts, fonts, etc) from dotneststatic.com without the Browser complaining ?

**Comment by Piedone** [comment]
Hi Olivier,

we're glad that you host your blogs at DotNest! This is indeed an error on our side, strange that we didn't notice it before. Let me look into it and see what we can do.

**Comment by Piedone** [comment]
Good news: this should be fixed now!
