### ISSUE TITLE
Sample Media Theme (NEST-379)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/DotNest-Support#44]
Provide an open-source sample Media Theme to help people work with the concept.

- Link this from the DotNest Knowledge Base and from the SDK's and Media Theme projects Readmes.
- Show Orchard could be like this.
- The theme in the SDK is kind of an example but a super simple one. It's not referenced anywhere either. It can remain but better would be a heavily documented sample, like the Training Demo module.
- You can take https://github.com/Piedone/DotNest-Sites as an inspiration.
- Demo at least the following:
  - Using custom CSS.
  - Adding custom favicons.
  - Overriding the Layout and a content shape.
  - Local development-ready setup recipe, with a separate export recipe that you use to refresh your local environment from your prod site. The All Content step should be configured not to export as a setup recipe (despite the recipe being used as setup recipe, so content item IDs will be hard-coded and thus content relationships kept). The Recipe File step should be added to configure the basic details of the recipe.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-379)

**Comment by wAsnk** [comment]
This got covered within https://github.com/Lombiq/Show-Orchard-Theme
