### ISSUE TITLE
Error when opening the Deployment Plans page if a Plan used the "Login settings" Step (NEST-471)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/DotNest-Support#50]
An Orchard Core upgrade broke the "Login settings" Deployment Step if you already used it in a Deployment Plan. While the current step works, if you had this step already, then the Deployment Plans admin page (/Admin/DeploymentPlan/Index) will be completely broken for you with an "An error occurred while executing this request." message.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-471)

**Comment by wAsnk** [comment]
It looks like the version difference caused this when we were between 1.7.0-preview and 1.7.0 version. It works in staging. 
Could you confirm it on your site in production, please?

**Comment by Piedone** [comment]
The error persists on my site.

**Comment by wAsnk** [comment]
This should be the repro steps, right?
1. Select a deployment plan that already existed with a login settings step.
![image](https://github.com/Lombiq/DotNest-Support/assets/19938236/a8a7c63d-e412-441b-909b-067b7c9fccb0)
2. Execute, File Download 
![image](https://github.com/Lombiq/DotNest-Support/assets/19938236/6f785679-7c92-4dd5-8d67-4b5c5d3b460c)

**Comment by Piedone** [comment]
No, you only have to do what I described in the issue, just visit /Admin/DeploymentPlan/Index:

![image](https://github.com/Lombiq/DotNest-Support/assets/1976647/74793cdc-ccef-4492-8e05-7a2ed2bd4fb6)

**Comment by wAsnk** [comment]
Check now please.

**Comment by Piedone** [comment]
It's good now!

**Comment by wAsnk** [comment]
Thank you! Closing this issue then.
