### ISSUE TITLE
Make it apparent on the Remote Clients page that you should deploy to the default subdomain (NEST-528)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/DotNest-Support#57]
Even if you use a custom domain, Remote Deployment, including Media Theme deployment should go the the default example.dotnest.net domain, [see docs](https://dotnest.com/knowledge-base/topics/custom-domains#:~:text=If%20you%20do%20Media%20Theme%20theming%20for%20your%20site%2C%20then%20be%20sure%20to%20keep%20remote%20deployments%20pointing%20still%20to%20your%20site%27s%20standard%20dotnest.net%20domain.%20You%20may%20get%20%22Remote%20deployment%20to%20...%20failed%20with%20the%20HTTP%20code%20Forbidden...%22%20errors%20due%20to%20Cloudflare%27s%20Bot%20Fight%20Mode%20otherwise.). To make this easier to know, change the default OC message on this screen to always show the default subdomain:

![image](https://github.com/Lombiq/DotNest-Support/assets/1976647/36c21ed4-75ff-4854-966c-46f9eee0f3c9)

Related: https://github.com/Lombiq/DotNest-Support/issues/56.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-528)

**Comment by wAsnk** [comment]
Fixed, and it is in production!

**Comment by Piedone** [comment]
Great!
