### ISSUE TITLE
DotNest Frontend - In case of creating a new site the option "Suspend" can be checked (NEST-348)

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#6]
At the moment in production environment the following error exists: when creating a new site, the user can check the "Suspended" checkbox, but this doesn't have any effect on creating a tenant and/or the setup, however, the site editor still shows that the Suspended option is checked. If I run the setup and afterward I want to suspend the site, then first I need to save the site editor while the suspended option is unchecked and then save it while it's checked again.

Solution: the option "Suspended" should be unreachable until the setup isn't run yet.

[Jira issue](https://lombiq.atlassian.net/browse/NEST-348)

**Comment by Piedone** [comment]
Let's remove the suspend feature altogether. We aren't using it for Orchard Core anyway.

**Comment by wAsnk** [comment]
Is it okay to remove the feature for new O1 tenants creation only? Or should it be removed entirely from everywhere, every part of its logic?

**Comment by Piedone** [comment]
Entirely, everywhere, but only from the UI. Pieces of it in the API client service and else can remain.
