### ISSUE TITLE
Finish Orchard RESTful API module

### ISSUE THREAD

**Issue by humanoidcreature** [Lombiq/DotNest-Support#9]
This would allow it to be apps and single page sites that are be able to use Orchard as content store on DotNest basis.

FYI: [Constrain clients to ones coming from the own app/website for unauthenticated web API](http://stackoverflow.com/questions/27963752/constrain-clients-to-ones-coming-from-the-own-app-website-for-unauthenticated-we)

So the API with single page apps will only be really usable after login.

**Comment by Hazzamanic** [comment]
Is a Rest api module something you are working on at Lombiq? Exclusively for dotnest? Sorry, just curious :)

**Comment by Piedone** [comment]
Not yet, it's just something on the list of things we'll do if we get bored :).

**Comment by Hazzamanic** [comment]
You guys have such a great attitude. Thanks for the prompt reply!

**Comment by Piedone** [comment]
We won't work on extending the O1 DotNest sites like this anymore. This is part of OC though.
